default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_demo_development

test:
  <<: *default
  database: rails_demo_test

production:
  <<: *default
  database: rails_demo_production
  username: rails_demo
  password: <%= ENV['RAILS_DEMO_DATABASE_PASSWORD'] %>
